- hosts: k8s-cluster
  gather_facts: False
  tasks:
    - ping:

- hosts: k8s-cluster
  gather_facts: False
  roles:
    - role: python2_install

- hosts: kube-node
  tags:
    - lvm-storage
  roles:
    - role: setup_lvm

- hosts: k8s-cluster
  gather_facts: False
  tags:
    - kubespray
  roles:
    - role: kubespray/roles/kubespray-defaults/
    - role: kubespray_var_patcher

- import_playbook: 'kubespray/cluster.yml'
  tags: kubespray

- hosts: kube-node
  tags:
    - lvm-storage
    - kube-pv
  roles:
    - role: kube_lvm_storage

- hosts: kube-master
  gather_facts: False
  roles:
    - role: kube_nginx_ingress
      tags: ['ingress']
    - role: kube_prometheus
      tags: ['kube-prometheus']
    - role: kube_heapster
      tags: ['heapster']
    - role: kube_elasticsearch
      tags: ['elasticsearch']
    - role: kube_metrics_server
      tags: ['metrics-server']
    - role: kube_cert_manager
      tags: ['cert-manager']
      when: cert_manager_self_sign|default(False)|bool

- hosts: k8s-cluster
  gather_facts: False
  roles:
    - role: info_displayer
      add_info:
        - master_dashboard_url: >-
            https://{{ kube_login }}:{{ kube_password }}@{{ ip_master }}:6443/ui
          kube_login: '{{ kube_login }}'
          kube_password: '{{ kube_password }}'
      vars:
        kube_login: 'kube'
        kube_password: >-
          {{ lookup('file', 'kubespray/credentials/kube_user') }}
        ip_master: >-
          {{ hostvars[groups['kube-master'][0]].ansible_default_ipv4.address }}
